[webservers]
web1 ansible_connection=local
web2 ansible_connection=local

[databases]
db1 ansible_connection=local
db2 ansible_connection=local

[loadbalancers]
lb1 ansible_connection=local

[frontend:children]
webservers
loadbalancers

[backend:children]
databases

[production:children]
frontend
backend
